### ISSUE TITLE
Implement Mantis Lords

### ISSUE THREAD

**Issue by RickLuiken** [Extremelyd1/HKMP#37]
I'm currently implementing the Mantis Lords fight.

**Comment by Extremelyd1** [comment]
Basically, someone can join the fight during the second phase when one of the mantis lords has been killed. If S2 is killed, everything works, as the state of throne 3 is set to defeated. If S1 is killed, the state of throne 3 is also set to defeated. As I linked the throne 3 state to S2, the client will receive that S2 is dead and will deactivate it. This means the last mantis lord will not move for the client and cannot die. That's why for now I added the force end, so the host can still kill the last mantis lord.

For the fix, both mantis lord classes (S1 and S2) should have access to the throne objects, so the client can determine whether S1 or S2 is dead when joining late.

_Originally posted by @RickLuiken in https://github.com/Extremelyd1/HKMP/issues/39#issuecomment-1005995250_

Keeping this issue open for the above reason.
